### ISSUE TITLE
Unusual activity detected 

### ISSUE THREAD

**Issue by 0xrushi** [SenZmaKi/Sengpt#2]
Unable to use sengpt after setting sengpt --session_token <mytoken>
```
 clichatgpt git:(main) ✗ sengpt hello

   You

  hello

   ChatGPT

Traceback (most recent call last):
  File "/Users/bread/opt/anaconda3/envs/311env/bin/sengpt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/site-packages/sengpt/main.py", line 307, in main
    asyncio.run(async_main())
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/site-packages/sengpt/main.py", line 272, in async_main
    _, update_is_available = await asyncio.gather(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/site-packages/sengpt/main.py", line 243, in gpt_coroutine
    await interactive_mode(SYS_ARGS, conversation)
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/site-packages/sengpt/main.py", line 188, in interactive_mode
    prompt_response = await fetch_prompt_response(prompt, conversation)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/site-packages/sengpt/main.py", line 163, in fetch_prompt_response
    async for resp_json in conversation.chat(prompt):
  File "/Users/bread/opt/anaconda3/envs/311env/lib/python3.11/site-packages/sengpt/re_gpt/async_chatgpt.py", line 142, in chat
    raise UnexpectedResponseError(error, server_response)
sengpt.re_gpt.errors.UnexpectedResponseError: An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.
This is what the server returned: data: {"message": {"id": "49915864-ae71-461b-9ea9-9f3bca0ef5f9", "author": {"role": "system", "name": null, "metadata": {}}, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": [""]}, "status": "finished_successfully", "end_turn": true, "weight": 0.0, "metadata": {"is_visually_hidden_from_conversation": true}, "recipient": "all"}, "conversation_id": "f597119e-fc22-4cda-9571-1d35b07b448b", "error": null}

data: {"message": {"id": "a72e835c-3bbf-41b1-9a59-12e8eada72c2", "author": {"role": "user", "name": null, "metadata": {}}, "create_time": 1711734339.75212, "update_time": null, "content": {"content_type": "text", "parts": ["hello"]}, "status": "finished_successfully", "end_turn": null, "weight": 1.0, "metadata": {"request_id": "86c1acc4bfcce853-DFW", "timestamp_": "absolute", "message_type": null}, "recipient": "all"}, "conversation_id": "f597119e-fc22-4cda-9571-1d35b07b448b", "error": null}

data: {"message": null, "conversation_id": "f597119e-fc22-4cda-9571-1d35b07b448b", "error": "Our systems have detected unusual activity from your system. Please try again later."}

.
```

**Comment by SenZmaKi** [comment]
Currently it uses [re_gpt](https://github.com/Zai-kun/reverse-engineered-chatgpt), which is still super buggy. So maybe try after a few hours or on the next day.

**Comment by 0xrushi** [comment]
This seems to be fixed, thanks!
